reddit:
  client_id: 8wlGeo867S2_Tv4pTmDPpQ
  client_secret: 4z3qMAvT4fN_sKuszBRrOm5tsJv-yQ
  username: BrotherOk1877
  password: Cham@2830
  user_agent: "RedditStoryBot/1.0 by /u/BrotherOk1877"
  subreddit: "amitheasshole"

openai:
  api_key: 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

elevenlabs:
  api_key: sk_fef2e6d7b00ba593e447852ed5d26b9232dae07b61422579
