reddit:
  client_id: 8wlGeo867S2_Tv4pTmDPpQ
  client_secret: 4z3qMAvT4fN_sKuszBRrOm5tsJv-yQ
  username: BrotherOk1877
  password: Cham@2830
  user_agent: "RedditStoryBot/1.0 by /u/BrotherOk1877"
  subreddit: "amitheasshole"

openai:
  api_key: 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
elevenlabs:
  api_key: sk_4b8c540f8c00d8db8cd126cc45c41c6324490eba60906656
