reddit:
  client_id: 8wlGeo867S2_Tv4pTmDPpQ
  client_secret: 4z3qMAvT4fN_sKuszBRrOm5tsJv-yQ
  username: BrotherOk1877
  password: Cham@2830
  user_agent: "RedditStoryBot/1.0 by /u/BrotherOk1877"
  subreddit: "amitheasshole"

openai:
  api_key: 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

elevenlabs:
  api_key: sk_fef2e6d7b00ba593e447852ed5d26b9232dae07b61422579
